version: 2
jobs:
  build:
    working_directory: /mpm
    docker:
      - image: docker:17.10.0-ce
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/mpm.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=mpm -t mpm .